tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_051.tar.gz ../OUTPUT/VPREM_051*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_052.tar.gz ../OUTPUT/VPREM_052*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_061.tar.gz ../OUTPUT/VPREM_061*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_liquid_001.tar.gz ../OUTPUT/VPREM_liquid_001*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_nCORE_001.tar.gz ../OUTPUT/VPREM_nCORE_001*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_nC_001B.tar.gz ../OUTPUT/VPREM_nC_001B*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_nVL_001B.tar.gz ../OUTPUT/VPREM_nVL_001B*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_nVL_liquid_001C.tar.gz ../OUTPUT/VPREM_nVL_liquid_001C*.*
