tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_crust.tar.gz ../OUTPUT/CSIMPLEMOON_crust*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_lcore300.tar.gz ../OUTPUT/CSIMPLEMOON_lcore300*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_score300.tar.gz ../OUTPUT/CSIMPLEMOON_score300*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_vlvl.tar.gz ../OUTPUT/CSIMPLEMOON_vlvl*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_Q2000.tar.gz ../OUTPUT/CSIMPLEMOON_Q2000*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_Q6500.tar.gz ../OUTPUT/CSIMPLEMOON_Q6500*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_basic.tar.gz ../OUTPUT/CSIMPLEMOON_basic*.*
