tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_001.tar.gz ../OUTPUT/PSVPREM_001*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_001b.tar.gz ../OUTPUT/PSVPREM_001b*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_002.tar.gz ../OUTPUT/PSVPREM_002*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_003.tar.gz ../OUTPUT/PSVPREM_003*.*


