tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSPACE_B_016.tar.gz ../OUTPUT/PSPACE_B_016*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSPACE_B_061.tar.gz ../OUTPUT/PSPACE_B_061*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSPACE_B_015.tar.gz ../OUTPUT/PSPACE_B_015*.*
