tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PBASIN_001.tar.gz ../OUTPUT/PBASIN_001*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PBASIN_002.tar.gz ../OUTPUT/PBASIN_002*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PBASIN_003.tar.gz ../OUTPUT/PBASIN_003*.*
