tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SINE_SS7.tar.gz ../OUTPUT/PSEARTH_SINE_SS7*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS1.tar.gz ../OUTPUT/PSEARTH_SS1*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS2.tar.gz ../OUTPUT/PSEARTH_SS2*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS3.tar.gz ../OUTPUT/PSEARTH_SS3*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS4.tar.gz ../OUTPUT/PSEARTH_SS4*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS5.tar.gz ../OUTPUT/PSEARTH_SS5*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS6.tar.gz ../OUTPUT/PSEARTH_SS6*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSEARTH_SS7.tar.gz ../OUTPUT/PSEARTH_SS7*.*
