tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_011.tar.gz ../OUTPUT/PSVPREM_011*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_012.tar.gz ../OUTPUT/PSVPREM_012*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_042.tar.gz ../OUTPUT/PSVPREM_042*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/PSVPREM_043.tar.gz ../OUTPUT/PSVPREM_043*.*