tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_Q2000_FirstS.tar.gz ../OUTPUT/CSIMPLEMOON_Q2000_FirstS*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_Q6500_FirstS.tar.gz ../OUTPUT/CSIMPLEMOON_Q6500_FirstS*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_basic_FirstS.tar.gz ../OUTPUT/CSIMPLEMOON_basic_FirstS*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/CSIMPLEMOON_basic_FirstS_dQ2.tar.gz ../OUTPUT/CSIMPLEMOON_basic_FirstS_dQ2*.*
