tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_082.tar.gz ../OUTPUT/VPREM_082*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_S3_001C.tar.gz ../OUTPUT/VPREM_S3_001C*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_S3_061.tar.gz ../OUTPUT/VPREM_S3_061*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_S3_062.tar.gz ../OUTPUT/VPREM_S3_062*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/VPREM_nCORE_012.tar.gz ../OUTPUT/VPREM_nCORE_012*.*
