tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/NBASIN_C_SL_sm_0005.tar.gz ../OUTPUT/NBASIN_C_SL_sm_0005*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/NBASIN_C_SL_sm_0010.tar.gz ../OUTPUT/NBASIN_C_SL_sm_0010*.*
tar -cvzf ../OUTPUT/TAR_GZ_OUTPUT/NBASIN_C_SL_sm_0015.tar.gz ../OUTPUT/NBASIN_C_SL_sm_0015*.*
