csh ./AVERAGING_SCRIPTS/PSPACE_014_average.csh
csh ./AVERAGING_SCRIPTS/PSPACE_022_average.csh
csh ./AVERAGING_SCRIPTS/PBASIN_001_average.csh
csh ./AVERAGING_SCRIPTS/PBASIN_002_average.csh
csh ./AVERAGING_SCRIPTS/PBASIN_003_average.csh
