csh ./AVERAGING_SCRIPTS/PSPACE_024_average.csh
csh ./AVERAGING_SCRIPTS/PSPACE_025_average.csh
csh ./AVERAGING_SCRIPTS/PSPACE_032_average.csh
csh ./AVERAGING_SCRIPTS/PSPACE_041_average.csh
csh ./AVERAGING_SCRIPTS/PSPACE_042_average.csh
csh ./AVERAGING_SCRIPTS/PSPACE_051_average.csh
