csh ./AVERAGING_SCRIPTS/PSPACE_B_001_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_Q2000_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_Q6500_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_basic_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_crust_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_lcore300_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_score300_average.csh
csh ./AVERAGING_SCRIPTS/CSIMPLEMOON_vlvl_average.csh
