csh ./AVERAGING_SCRIPTS/RSMOON_011a_average.csh
csh ./AVERAGING_SCRIPTS/RSMOON_012a_average.csh
csh ./AVERAGING_SCRIPTS/RSMOON_012c_average.csh
csh ./AVERAGING_SCRIPTS/RVPREM_001_average.csh
csh ./AVERAGING_SCRIPTS/RVPREM_002_average.csh
