csh ./AVERAGING_SCRIPTS/PSPACE_B_022_average.csh
csh ./AVERAGING_SCRIPTS/PSVPREM_001_average.csh
csh ./AVERAGING_SCRIPTS/PSVPREM_001b_average.csh
csh ./AVERAGING_SCRIPTS/PSVPREM_002_average.csh
csh ./AVERAGING_SCRIPTS/PSVPREM_003_average.csh
